name: test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Run Paddle test task'
        uses: .github/actions
        with:
          task: ':paddle_example_root:some_tests'

