name: test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JB_SPACE_CLIENT_ID: ${{ secrets.JB_SPACE_CLIENT_ID }}
      JB_SPACE_CLIENT_SECRET: ${{ secrets.JB_SPACE_CLIENT_SECRET }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build Docker image'
        run: docker build -t paddle-example --build-arg JB_SPACE_CLIENT_ID=$JB_SPACE_CLIENT_ID --build-arg JB_SPACE_CLIENT_SECRET=$JB_SPACE_CLIENT_SECRET .

      - name: 'Run tests'
        run: docker run paddle-example :paddle_example_root:some_tests
